### ISSUE TITLE
[Bug] Sample Script Fails to Include TM in Project

### ISSUE THREAD

**Issue by ghost** [RWS/Sdl-studio-powershell-toolkit#2]
Studio Version: 2017 SR1
Operating System: Windows Server 2012

The sample script provided with the modules fails to save the TM it creates as a translation provider in the project it creates. I am uncertain as to whether this problem is inherent to the Studio API, or whether it is to do with Powershell or these otherwise wonderful modules you've created, and several days searching have yet to solve the problem. Any clues as to why it's not working?

**Comment by ghost** [comment]
Another week and I think I've found the solution;

In ProjectHelper.psm1, right before calling
$fileBasedProject.UpdateTranslationProviderConfiguration($tmTargetLanguage, $tmConfig);
you need to call
$tmConfig.OverrideParent = $true;

**Comment by cromica** [comment]
Thanks. We'll make the changes.
